manga-dl fixes

diff --git a/.local/bin/manga-dl b/.local/bin/manga-dl
--- a/.local/bin/manga-dl
+++ b/.local/bin/manga-dl
@@ -55,8 +55,7 @@ process_url() {
 
 # Prepare urls
 prepare_urls() {
-	set_site || return 1
-	generate_urls || return 1
+	set_site && generate_urls
 }
 set_site() {
 	case "$link" in
@@ -90,15 +89,15 @@ download_urls() {
 	mkdir -p "$savedir"
 	cd       "$savedir"
 	case ${rename_images[$site]} in
-	0) download_orig ;;
+	0) download_original ;;
 	1) download_numbered ;;
 	2) download_prefixed ;;
 	esac
-	sxiv -r . </dev/null >/dev/null &
+	sxiv -r . </dev/null >/dev/null 2>&1 &
 	exec 11<&-
 }
 
-download_orig() {
+download_original() {
 	local url
 	while read_url
 	do
@@ -110,13 +109,13 @@ download_orig() {
 	done
 }
 download_numbered() {
-	local i=1
+	local url i=1
 	while read_url
 	do wget "$url" "-O$(printf "%03d" $i).jpg" && ((++i))
 	done
 }
 download_prefixed() {
-	local i=1
+	local url i=1
 	while read_url
 	do wget "$url" "-O$(printf "%03d" $i)_$(basename "$url")" && ((++i))
 	done
@@ -127,6 +126,7 @@ wget() { command wget "${wget_opts[@]}" "--referer=$link" "$@" ;}
 
 # wget opts
 cookie_file=$(mktemp)
+trap "{ rm '$cookie_file'; }" EXIT
 wget_opts=(--tries 0)
 wget_opts+=(--timeout 60)
 wget_opts+=(--continue)
@@ -148,7 +148,7 @@ name_regex[mangacow]='(.* - Chapter [^-]*) -'
 name_regex[webtoons]='(.*)<\/title>'
 name_regex[mangastream]='(.*)\ -'
 name_regex[foolslide]='(.*::.*) :: '
-name_regex[mangadex]='.*\((.*)\) - MangaDex'
+name_regex[mangadex]='(.*\(.*\)) - MangaDex'
 
 # if 0, do not rename
 # if 1, renumber completely
@@ -171,8 +171,8 @@ extract_title() {
 	[ "$title" ] || { err "unable to get name from url\\n"; return 1; }
 }
 extract_page_count() {
-	# Remember to quit
 	pages=$(sed -nr "$1" <&10)
+	[ "$pages" ] || { err "unable to get page count from url\\n"; return 1; }
 }
 output_urls_from_args() {
 	local urls=("$@")
@@ -197,26 +197,26 @@ output_urls_from_page() {
 
 # Site Processing function
 process_gos_moe() {
-	extract_title || return 1
+	extract_title &&
 	output_urls_from_page "/alt=\"$title/{s/.*src=\"([^\"]*)\".*/\\1/;p}"
 }
 process_webtoons() {
-	extract_title || return 1
+	extract_title &&
 	output_urls_from_page '/class="_images"/{s/.*data-url="([^"]*)".*/\1/;p}'
 }
 process_mangacow() {
-	extract_title || return 1
-	exec 10< <(tr ';' '\n' <&10)
+	extract_title &&
+	exec 10< <(tr ';' '\n' <&10) &&
 	output_urls_from_page '/arr_img.push/{s/.*"([^"]*)".*/\1/;p}'
 }
 process_mangastream() {
-	extract_title || return 1
-	extract_page_count '/a href.*Last Page/{s|.*/([0-9]*)">Last Page.*|\1|;p;q}';
+	extract_title &&
+	extract_page_count '/a href.*Last Page/{s|.*/([0-9]*)">Last Page.*|\1|;p;q}' &&
 	output_urls_from_pages "$(dirname "$link")" '/id="manga-page"/{s/.*src="([^"]*)".*/http:\1/;p}'
 }
 process_foolslide() {
-	extract_title || return 1
-	extract_page_count '/tbtitle dropdown_parent dropdown_right/{s/.*>([0-9]*) .*/\1/;p;q}'
+	extract_title &&
+	extract_page_count '/tbtitle dropdown_parent dropdown_right/{s/.*>([0-9]*) .*/\1/;p;q}' &&
 	output_urls_from_pages "$(dirname "$link")" '\,content/comics/,{s/.*src="([^"]*)".*/\1/;p}'
 }
 process_imgur() {
@@ -233,23 +233,22 @@ process_imgursolo() {
 }
 process_mangadex() {
 	extract_title || return 1
-	local page
+	local page webtoon
 	# Supress showing page contents in debug
 	$debug && set +x
 	page="$(cat <&10)"
 	$debug && set -x
-	local webtoon
-	mapfile -t webtoon < <(sed -nr '/class="webtoon/{s/.*img.*src="([^"]*)".*/\1/;p}' <<< "$page")
+	# some pages have the mangadex part, others use relative url
+	local url_regex='s_.*img.*src="((.*)mangadex.org|)([^"]*)".*_\2mangadex.org/\3_'
+	mapfile -t webtoon < <(sed -nr '/class="webtoon/{'"$url_regex"';p}' <<< "$page")
 	if [ "${#webtoon[@]}" -gt 0 ]
 	then output_urls_from_args "${webtoon[@]}"
 	else
 		pages=$(sed -nr '/Page 1/{s/.*Page ([0-9]*).*/\1/;p;q}' <<< "$page")
-		output_urls_from_pages "$link" '/id="current_page"/{s/.*img.*src="([^"]*)".*/\1/;p}'
+		output_urls_from_pages "$link" '/id="current_page"/{'"$url_regex"';p}'
 	fi
 }
-#}}}
 
 for url
 do process_url "$@"
 done
-rm "$cookie_file"
